version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  main:
    jobs:
      - build
      - push
jobs:
  build:
    machine:
      image: ubuntu-1604:202101-01
    steps:
      - checkout
      - run:
          name: "Build docker"
          command: make build
  push:
    machine:
      image: ubuntu-1604:202101-01
    steps:
      - run:
          name: "Docker login"
          command: make login
      - run:
          name: "Push latest"
          command: make push
